### ISSUE TITLE
Add Oauth2 Provider like Gitea

### ISSUE THREAD

**Issue by v7lin** [thomseddon/traefik-forward-auth#91]
Add Oauth2 Provider like Gitea

**Comment by thomseddon** [comment]
It's a shame they don't support openid connect ☹️ but yes, I think this would make sense 👍

**Comment by Kiina** [comment]
Wouldn't it be possible to just add generic oauth2 instead of specific providers? Sure you would have to set a few more variables to setup for the endpoints, but it would make it work with any oauth2 provider which follows the specification. Only taking a quick look at the Google Provider I can't see much reason why the user couldn't just set `LoginURL, TokenURL, UserURL` to use any generic oauth2 provider. Or am I missing something?

**Comment by thomseddon** [comment]
That may certainly work actually! Most providers now support openid (including Google) so that should work for most.
The main argument for individual providers is simplicity and to capture any implementation specifics (such as the select account prompt for Google).

But a generic provider sounds like it could work here, I may go for this instead!

**Comment by thomseddon** [comment]
Looking at the gitea API, it requires the token to be prefixed with `token` "for legacy reasons".
So that that will need to be configurable.

**Comment by thomseddon** [comment]
This should now work in #138 with the following options:
```
--providers.generic-oauth.auth-url=<gitea url>/login/oauth/authorize
--providers.generic-oauth.token-url=<gitea url>/login/oauth/access_token
--providers.generic-oauth.user-url=<gitea url>/api/v1/user
--providers.generic-oauth.client-id=<gitea client id>
--providers.generic-oauth.client-secret=<gitea client secret>
--providers.generic-oauth.token-style=query_string
```

I'll try to setup gitea to give this a test

**Comment by thomseddon** [comment]
Very happy to say that support for Gitea has been released in v2.2, there's some guidance on the setup [here](https://github.com/thomseddon/traefik-forward-auth/wiki/Provider-Setup#gitea)

That you @Kiina for the idea of a "generic" provider, that's exactly what I've done and I think it's worked really well :)

**Comment by v7lin** [comment]
@thomseddon i don't known how to setup gitea redirect url？

**Comment by DrizztDU** [comment]
> @thomseddon i don't known how to setup gitea redirect url？

if you request to `https://myapp.com`, the redirect url is `https://myapp.com/_oauth`. -> [Doc](https://github.com/thomseddon/traefik-forward-auth#overlay-mode)

**Comment by v7lin** [comment]
@DrizztDU thanks
